package aishell

import (
	"bytes"
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

//go:embed scripts/bootstrap-tools.sh
var bootstrapToolsSh string

//go:embed scripts/setup-git-ssh.sh
var setupGitSshSh string

//go:embed scripts/Dockerfile.apt.tmpl
var dockerfileTmplApt string

//go:embed scripts/Dockerfile.dnf.tmpl
var dockerfileTmplDnf string

//go:embed scripts/Dockerfile.zypper.tmpl
var dockerfileTmplZypper string

//go:embed scripts/Dockerfile.pacman.tmpl
var dockerfileTmplPacman string

const (
	markerOpen  = "# === AI-SHELL AUTO-GENERATED — DO NOT EDIT BELOW THIS LINE ==="
	markerClose = "# === AI-SHELL AUTO-GENERATED — DO NOT EDIT ABOVE THIS LINE ==="
)

var dockerfileTmpls = map[string]string{
	"apt":    dockerfileTmplApt,
	"dnf":    dockerfileTmplDnf,
	"zypper": dockerfileTmplZypper,
	"pacman": dockerfileTmplPacman,
}

type dockerfileData struct {
	BaseImage string
}

// generateDockerfile renders the auto-generated section of the Dockerfile
// (including markers) for the given family and base image.
func generateDockerfile(baseImage, family string) (string, error) {
	tmplStr, ok := dockerfileTmpls[family]
	if !ok {
		return "", fmt.Errorf("no Dockerfile template for family %q", family)
	}
	t, err := template.New("Dockerfile").Parse(tmplStr)
	if err != nil {
		return "", fmt.Errorf("failed to parse Dockerfile template for %q: %w", family, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, dockerfileData{BaseImage: baseImage}); err != nil {
		return "", fmt.Errorf("failed to render Dockerfile template for %q: %w", family, err)
	}

	var sb strings.Builder
	sb.WriteString(markerOpen + "\n")
	sb.WriteString(buf.String())
	sb.WriteString(markerClose + "\n")
	return sb.String(), nil
}

// defaultCustomSection is appended after the closing marker on first init.
func defaultCustomSection() string {
	return `
# Add your customizations below (extra packages, config, etc.).
# This section is preserved when you run 'ai-shell init --force'.
`
}

// spliceDockerfile replaces the auto-generated section in an existing Dockerfile
// while preserving everything outside the markers.
// Returns an error if the markers are not found.
func spliceDockerfile(existing, newAutoSection string) (string, error) {
	openIdx := strings.Index(existing, markerOpen)
	if openIdx < 0 {
		return "", fmt.Errorf("opening marker not found in existing Dockerfile")
	}
	closeIdx := strings.Index(existing, markerClose)
	if closeIdx < 0 {
		return "", fmt.Errorf("closing marker not found in existing Dockerfile")
	}
	closeEnd := closeIdx + len(markerClose)
	if closeEnd < len(existing) && existing[closeEnd] == '\n' {
		closeEnd++
	}

	before := existing[:openIdx]
	after := existing[closeEnd:]

	return before + newAutoSection + after, nil
}

// generateComposeOverrideYAML returns the docker-compose.override.yml content.
func generateComposeOverrideYAML() string {
	var sb strings.Builder
	sb.WriteString("# docker-compose.override.yml\n")
	sb.WriteString("# Add your project-specific customizations here.\n")
	sb.WriteString("# This file is merged with docker-compose.yml automatically by docker compose / podman-compose.\n")
	sb.WriteString("# It is NOT overwritten by 'ai-shell init' or 'ai-shell regen'.\n")
	sb.WriteString("#\n")
	sb.WriteString("# Examples:\n")
	sb.WriteString("#   services:\n")
	sb.WriteString("#     ai-shell:\n")
	sb.WriteString("#       environment:\n")
	sb.WriteString("#         - MY_VAR=value\n")
	sb.WriteString("#       volumes:\n")
	sb.WriteString("#         - /extra/path:/extra/path\n")
	sb.WriteString("#       ports:\n")
	sb.WriteString("#         - \"8080:8080\"\n")
	sb.WriteString("\n")
	sb.WriteString("services:\n")
	sb.WriteString("  ai-shell: {}\n")
	return sb.String()
}

// generateComposeYAML returns the docker-compose.yml content for export.
func generateComposeYAML(iid, container, image, volume, baseImage string) string {
	var sb strings.Builder

	sb.WriteString("# Generated by ai-shell — do not edit by hand.\n")
	sb.WriteString("# Use docker-compose.override.yml for customizations.\n")
	sb.WriteString("# Works with both docker compose and podman-compose\n")
	sb.WriteString("#\n")
	sb.WriteString("# Note: workdir is discovered from the /work bind mount (..:/work),\n")
	sb.WriteString("# so this file is portable across machines.\n")
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("name: ai-shell-%s\n", iid))
	sb.WriteString("\n")
	sb.WriteString("services:\n")
	sb.WriteString("  ai-shell:\n")
	sb.WriteString("    build:\n")
	sb.WriteString("      context: .\n")
	sb.WriteString("      args:\n")
	sb.WriteString(fmt.Sprintf("        - BASE_IMAGE=${BASE_IMAGE:-%s}\n", baseImage))
	sb.WriteString(fmt.Sprintf("    image: %s\n", image))
	sb.WriteString(fmt.Sprintf("    container_name: %s\n", container))
	sb.WriteString("    labels:\n")
	sb.WriteString(fmt.Sprintf("      %s: \"true\"\n", LabelManaged))
	sb.WriteString(fmt.Sprintf("      %s: \"1\"\n", LabelSchema))
	sb.WriteString(fmt.Sprintf("      %s: \"%s\"\n", LabelInstance, iid))
	sb.WriteString(fmt.Sprintf("      %s: \"%s\"\n", LabelVolume, volume))
	sb.WriteString("    volumes:\n")
	sb.WriteString("      - ..:/work                           # parent dir = workdir (source of truth)\n")
	sb.WriteString(fmt.Sprintf("      - %s:/root\n", volume))
	sb.WriteString("      - ${HOME}/.config/cursor:/root/.config/cursor:ro\n")
	sb.WriteString("      - ${HOME}/.claude:/root/.claude:ro\n")
	sb.WriteString("    env_file:\n")
	sb.WriteString("      - path: ${AI_SHELL_ENV_FILE:-/dev/null}\n")
	sb.WriteString("        required: false\n")
	sb.WriteString("    command: [\"sh\", \"-c\", \"while true; do sleep 3600; done\"]\n")
	sb.WriteString("\n")
	sb.WriteString("volumes:\n")
	sb.WriteString(fmt.Sprintf("  %s:\n", volume))
	sb.WriteString("    external: false\n")

	return sb.String()
}

// generateReadme returns the README.md content for the .ai-shell directory.
func generateReadme(container string) string {
	return fmt.Sprintf(`# ai-shell Configuration

This directory contains the ai-shell configuration for this project.

## Usage

### Initialize and start (recommended)

%s
ai-shell up
%s

### Or use Docker Compose directly

%s
docker compose up -d --build
%s

Or with podman-compose (install via `+"`pipx install podman-compose`"+`):

%s
podman-compose up -d --build
%s

### Enter the container

%s
ai-shell enter
# or: docker compose exec ai-shell bash
%s

### Setup Git SSH access

%s
docker compose exec ai-shell sh /work/.ai-shell/setup-git-ssh.sh
%s

### Stop the container

%s
ai-shell stop
# or: docker compose down
%s

## Notes

- The parent directory (your project) is mounted at `+"`/work`"+` inside the container
- Scripts are accessed from `+"`/work/.ai-shell/`"+` (this directory, mounted)
- The `+"`/root`"+` directory is persisted in a named volume
- Cursor config is mounted read-only from `+"`~/.config/cursor`"+`
- Claude config is mounted read-only from `+"`~/.claude`"+`
- The `+"`ai-shell`"+` CLI commands (`+"`ai-shell status`"+`, `+"`ai-shell enter`"+`, etc.) work with this container
- Set `+"`AI_SHELL_ENV_FILE`"+` environment variable to inject secrets (e.g., `+"`GH_TOKEN`"+`)

## Customization

- `+"`Dockerfile`"+`: The auto-generated section (between markers) installs base tools. Add your own packages below the closing marker — they are preserved by `+"`ai-shell init --force`"+`.
- `+"`docker-compose.override.yml`"+`: Add volume mounts, environment variables, ports, services — never overwritten by ai-shell.
- `+"`bootstrap-tools.sh`"+`: Optional runtime hook — runs on every `+"`ai-shell up`"+`. Add commands here for tools that must be installed at runtime (e.g., into the persistent /root volume).
- `+"`setup-git-ssh.sh`"+`: Customize SSH/git setup.

**Note:** `+"`docker-compose.yml`"+` is auto-generated — do not edit it by hand. Use `+"`docker-compose.override.yml`"+` instead.
To regenerate `+"`docker-compose.yml`"+` with a new instance ID, run `+"`ai-shell regen --base-image <alias>`"+`.

Container name: `+"`%s`"+`
`, "```bash", "```", "```bash", "```", "```bash", "```", "```bash", "```", "```bash", "```", "```bash", "```", container)
}

// exportFiles writes all export files to the output directory.
func exportFiles(outputDir, workdir string, cfg *Config, baseImage, family string, force bool) error {
	containerBase, imageBase, volumeBase := resolveBases(cfg)
	iid := InstanceID(workdir)
	container, volume := NamesFor(workdir, containerBase, volumeBase)
	image := imageBase + "-" + iid

	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Files managed by init (checked for existence when not forcing).
	// docker-compose.override.yml is excluded — never overwritten regardless of --force.
	files := []string{"Dockerfile", "docker-compose.yml", "bootstrap-tools.sh", "setup-git-ssh.sh", "README.md"}
	if !force {
		var existing []string
		for _, f := range files {
			p := filepath.Join(outputDir, f)
			if _, err := os.Stat(p); err == nil {
				existing = append(existing, f)
			}
		}
		if len(existing) > 0 {
			return fmt.Errorf("files already exist in %s: %s\nUse --force to overwrite", outputDir, strings.Join(existing, ", "))
		}
	}

	// Generate Dockerfile auto-generated section
	autoSection, err := generateDockerfile(baseImage, family)
	if err != nil {
		return fmt.Errorf("failed to generate Dockerfile: %w", err)
	}

	dockerfilePath := filepath.Join(outputDir, "Dockerfile")
	if force {
		// Try to splice: preserve user customizations below the closing marker.
		existingContent, readErr := os.ReadFile(dockerfilePath)
		if readErr == nil {
			spliced, spliceErr := spliceDockerfile(string(existingContent), autoSection)
			if spliceErr == nil {
				if err := os.WriteFile(dockerfilePath, []byte(spliced), 0o644); err != nil {
					return fmt.Errorf("failed to write Dockerfile: %w", err)
				}
			} else {
				fmt.Fprintf(os.Stderr, "Warning: markers not found in existing Dockerfile; overwriting entirely.\n")
				if err := os.WriteFile(dockerfilePath, []byte(autoSection+defaultCustomSection()), 0o644); err != nil {
					return fmt.Errorf("failed to write Dockerfile: %w", err)
				}
			}
		} else {
			if err := os.WriteFile(dockerfilePath, []byte(autoSection+defaultCustomSection()), 0o644); err != nil {
				return fmt.Errorf("failed to write Dockerfile: %w", err)
			}
		}
	} else {
		if err := os.WriteFile(dockerfilePath, []byte(autoSection+defaultCustomSection()), 0o644); err != nil {
			return fmt.Errorf("failed to write Dockerfile: %w", err)
		}
	}

	// Generate and write docker-compose.yml
	composeContent := generateComposeYAML(iid, container, image, volume, baseImage)
	if err := os.WriteFile(filepath.Join(outputDir, "docker-compose.yml"), []byte(composeContent), 0o644); err != nil {
		return fmt.Errorf("failed to write docker-compose.yml: %w", err)
	}

	// Write docker-compose.override.yml only if it does not already exist.
	overridePath := filepath.Join(outputDir, "docker-compose.override.yml")
	if _, err := os.Stat(overridePath); os.IsNotExist(err) {
		overrideContent := generateComposeOverrideYAML()
		if err := os.WriteFile(overridePath, []byte(overrideContent), 0o644); err != nil {
			return fmt.Errorf("failed to write docker-compose.override.yml: %w", err)
		}
	}

	// Write helper scripts
	scripts := []struct {
		name    string
		content string
		perm    os.FileMode
	}{
		{"bootstrap-tools.sh", bootstrapToolsSh, 0o755},
		{"setup-git-ssh.sh", setupGitSshSh, 0o755},
	}
	for _, s := range scripts {
		dstPath := filepath.Join(outputDir, s.name)
		if err := os.WriteFile(dstPath, []byte(s.content), s.perm); err != nil {
			return fmt.Errorf("failed to write %s: %w", s.name, err)
		}
	}

	// Generate and write README.md
	readmeContent := generateReadme(container)
	if err := os.WriteFile(filepath.Join(outputDir, "README.md"), []byte(readmeContent), 0o644); err != nil {
		return fmt.Errorf("failed to write README.md: %w", err)
	}

	return nil
}
